using CodecBzip2
using Base.Test
import TranscodingStreams: test_roundtrip_read, test_roundtrip_write

@testset "Bzip2 Codec" begin
    # Generated by `bz2.compress(b"foo")` on CPython 3.5.2.
    data = b"BZh91AY&SYI\xfe\xc4\xa5\x00\x00\x00\x01\x00\x01\x00\xa0\x00!\x00\x82,]\xc9\x14\xe1BA'\xfb\x12\x94"
    @test read(Bzip2DecompressionStream(IOBuffer(data))) == b"foo"

    test_roundtrip_read(Bzip2CompressionStream, Bzip2DecompressionStream)
    test_roundtrip_write(Bzip2CompressionStream, Bzip2DecompressionStream)
end
